package reporter

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/dovocoder/gollaw/internal/analyzer"
)

// FormatPRSummary renders a sticky PR summary comment in markdown for GitHub PRs.
// Shows status emoji, health score badge, and at most 10 findings.
func FormatPRSummary(report *Report) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "## 🤖 Gollaw Code Review\n\n")

	// Determine status.
	statusEmoji := "✅"
	statusText := "pass"
	if report.HealthScore.Score < 70 || hasSeverity(report.Findings, analyzer.SeverityCritical) {
		statusEmoji = "❌"
		statusText = "fail"
	} else if len(report.Findings) > 0 {
		statusEmoji = "⚠️"
		statusText = "warn"
	}

	fmt.Fprintf(&buf, "**Status:** %s %s\n\n", statusEmoji, statusText)

	// Health score badge.
	fmt.Fprintf(&buf, "**Health Score:** %d/100 (Grade: %s)\n\n", report.HealthScore.Score, report.HealthScore.Grade)

	// Counts summary.
	fmt.Fprintf(&buf, "**Findings:** %d total", report.Summary.Total)
	if report.Summary.Total > 0 {
		parts := make([]string, 0, 4)
		for _, sev := range []analyzer.Severity{analyzer.SeverityCritical, analyzer.SeverityWarning, analyzer.SeverityInfo, analyzer.SeverityHint} {
			if c := report.Summary.BySeverity[string(sev)]; c > 0 {
				parts = append(parts, fmt.Sprintf("%d %s", c, sev))
			}
		}
		fmt.Fprintf(&buf, " (%s)", strings.Join(parts, ", "))
	}
	fmt.Fprintf(&buf, "\n\n")

	// Top findings table (max 10).
	if len(report.Findings) > 0 {
		findings := make([]analyzer.Finding, len(report.Findings))
		copy(findings, report.Findings)
		sort.Slice(findings, func(i, j int) bool {
			return severityPriorityValue(findings[i].Severity) < severityPriorityValue(findings[j].Severity)
		})

		maxShow := 10
		shown := findings
		remaining := 0
		if len(findings) > maxShow {
			shown = findings[:maxShow]
			remaining = len(findings) - maxShow
		}

		fmt.Fprintf(&buf, "### Top Findings\n\n")
		fmt.Fprintf(&buf, "| # | Severity | File:Line | Message |\n")
		fmt.Fprintf(&buf, "|---|----------|-----------|---------|\n")
		for i, f := range shown {
			fmt.Fprintf(&buf, "| %d | %s | %s:%d | %s |\n",
				i+1, strings.ToUpper(string(f.Severity)), f.File, f.Line, f.Message)
		}
		if remaining > 0 {
			fmt.Fprintf(&buf, "\n_...and %d more_\n", remaining)
		}
		fmt.Fprintf(&buf, "\n")
	} else {
		fmt.Fprintf(&buf, "_No findings — great job! 🎉_\n\n")
	}

	fmt.Fprintf(&buf, "---\n_Generated by Gollaw v%s_\n", report.Version)

	return buf.Bytes(), nil
}

func hasSeverity(findings []analyzer.Finding, sev analyzer.Severity) bool {
	for _, f := range findings {
		if f.Severity == sev {
			return true
		}
	}
	return false
}
