package reporter

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/dovocoder/gollaw/internal/analyzer"
)

// formatPRSummary renders a sticky PR summary comment in markdown for GitHub PRs.
// Shows status emoji, health score badge, and at most 10 findings.
func formatPRSummary(report *Report) ([]byte, error) {
	var buf bytes.Buffer

	writePRSummaryHeader(&buf, report)
	writePRSummaryCounts(&buf, report)
	writePRSummaryFindings(&buf, report)

	fmt.Fprintf(&buf, "---\n_Generated by Gollaw v%s_\n", report.Version)
	return buf.Bytes(), nil
}

func writePRSummaryHeader(buf *bytes.Buffer, report *Report) {
	fmt.Fprintf(buf, "## 🤖 Gollaw Code Review\n\n")

	statusEmoji, statusText := prSummaryStatus(report)
	fmt.Fprintf(buf, "**Status:** %s %s\n\n", statusEmoji, statusText)
	fmt.Fprintf(buf, "**Health Score:** %d/100 (Grade: %s)\n\n", report.HealthScore.Score, report.HealthScore.Grade)
}

func prSummaryStatus(report *Report) (emoji, text string) {
	if report.HealthScore.Score < 70 || hasSeverity(report.Findings, analyzer.SeverityCritical) {
		return "❌", "fail"
	}
	if len(report.Findings) > 0 {
		return "⚠️", "warn"
	}
	return "✅", "pass"
}

func writePRSummaryCounts(buf *bytes.Buffer, report *Report) {
	fmt.Fprintf(buf, "**Findings:** %d total", report.Summary.Total)
	if report.Summary.Total > 0 {
		parts := make([]string, 0, 4)
		for _, sev := range []analyzer.Severity{analyzer.SeverityCritical, analyzer.SeverityWarning, analyzer.SeverityInfo, analyzer.SeverityHint} {
			if c := report.Summary.BySeverity[string(sev)]; c > 0 {
				parts = append(parts, fmt.Sprintf("%d %s", c, sev))
			}
		}
		fmt.Fprintf(buf, " (%s)", strings.Join(parts, ", "))
	}
	fmt.Fprintf(buf, "\n\n")
}

func writePRSummaryFindings(buf *bytes.Buffer, report *Report) {
	if len(report.Findings) == 0 {
		fmt.Fprintf(buf, "_No findings — great job! 🎉_\n\n")
		return
	}

	findings := make([]analyzer.Finding, len(report.Findings))
	copy(findings, report.Findings)
	sort.Slice(findings, func(i, j int) bool {
		return severityPriorityValue(findings[i].Severity) < severityPriorityValue(findings[j].Severity)
	})

	shown, remaining := limitFindings(findings, 10)

	fmt.Fprintf(buf, "### Top Findings\n\n")
	fmt.Fprintf(buf, "| # | Severity | File:Line | Message |\n")
	fmt.Fprintf(buf, "|---|----------|-----------|--------|\n")
	for i, f := range shown {
		fmt.Fprintf(buf, "| %d | %s | %s:%d | %s |\n",
			i+1, strings.ToUpper(string(f.Severity)), f.File, f.Line, f.Message)
	}
	if remaining > 0 {
		fmt.Fprintf(buf, "\n_...and %d more_\n", remaining)
	}
	fmt.Fprintf(buf, "\n")
}

func limitFindings(findings []analyzer.Finding, maxShow int) (shown []analyzer.Finding, remaining int) {
	if len(findings) > maxShow {
		return findings[:maxShow], len(findings) - maxShow
	}
	return findings, 0
}

func hasSeverity(findings []analyzer.Finding, sev analyzer.Severity) bool {
	for _, f := range findings {
		if f.Severity == sev {
			return true
		}
	}
	return false
}
