package analyzer

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dovocoder/gollaw/internal/loader"
)

func TestUnusedAnalyzerRequiresActualExternalReference(t *testing.T) {
	findings := analyzeUnusedModule(t, map[string]string{
		"go.mod": "module sample\n\ngo 1.25\n",
		"lib/lib.go": `package lib

func Used() {}

func Unused() {}
`,
		"main.go": `package main

import "sample/lib"

func main() {
	lib.Used()
}
`,
	})

	assertUnusedNotContains(t, findings, "Used")
	assertUnusedContains(t, findings, "Unused")
}

func TestUnusedAnalyzerKeepsExportedSignatureTypes(t *testing.T) {
	findings := analyzeUnusedModule(t, map[string]string{
		"go.mod": "module sample\n\ngo 1.25\n",
		"lib/lib.go": `package lib

type Client struct{}

func NewClient() *Client {
	return &Client{}
}
`,
		"main.go": `package main

import "sample/lib"

func main() {
	_ = lib.NewClient()
}
`,
	})

	assertUnusedNotContains(t, findings, "Client")
}

func TestUnusedAnalyzerSkipsBuildInjectedVars(t *testing.T) {
	findings := analyzeUnusedModule(t, map[string]string{
		"go.mod": "module sample\n\ngo 1.25\n",
		"main.go": `package main

// Version is set at build time via -ldflags "-X sample.Version=v1.0.0".
var Version = "dev"

func main() {}
`,
	})

	assertUnusedNotContains(t, findings, "Version")
}

func TestUnusedAnalyzerSkipsGeneratedExports(t *testing.T) {
	findings := analyzeUnusedModule(t, map[string]string{
		"go.mod": "module sample\n\ngo 1.25\n",
		"storedb/models.go": `// Code generated by sqlc. DO NOT EDIT.

package storedb

type GeneratedRow struct{}
`,
	})

	assertUnusedNotContains(t, findings, "GeneratedRow")
}

func analyzeUnusedModule(t *testing.T, files map[string]string) []Finding {
	t.Helper()

	dir := t.TempDir()
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("write %s: %v", path, err)
		}
	}

	loaded, err := loader.Load(loader.LoadConfig{Dir: dir, Patterns: []string{"./..."}})
	if err != nil {
		t.Fatalf("load module: %v", err)
	}
	ctx := &Context{
		FSET:        loaded.FSET,
		Packages:    loaded.Packages,
		TypesByPkg:  loaded.TypesByPkg,
		SyntaxByPkg: loaded.SyntaxByPkg,
	}
	findings, err := newUnusedAnalyzer().Analyze(ctx)
	if err != nil {
		t.Fatalf("analyze unused: %v", err)
	}
	return findings
}

func assertUnusedContains(t *testing.T, findings []Finding, name string) {
	t.Helper()
	for _, finding := range findings {
		if finding.RuleID == "GLW-UU001" && strings.Contains(finding.Message, name) {
			return
		}
	}
	t.Fatalf("unused findings do not contain %q: %+v", name, findings)
}

func assertUnusedNotContains(t *testing.T, findings []Finding, name string) {
	t.Helper()
	for _, finding := range findings {
		if finding.RuleID == "GLW-UU001" && strings.Contains(finding.Message, name) {
			t.Fatalf("unused findings unexpectedly contain %q: %+v", name, findings)
		}
	}
}
